# Generated by Django 5.0.2 on 2025-06-28 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
